import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { Progress } from '@/components/ui/progress';
import { 
  Download, 
  FileText, 
  TrendingUp, 
  Calendar, 
  DollarSign,
  PieChart,
  Shield,
  Target,
  CheckCircle
} from 'lucide-react';

interface ReportCardProps {
  userData: any;
}

export const ReportCard = ({ userData }: ReportCardProps) => {
  const investmentAmount = parseInt(userData.investmentAmount) || 0;
  const riskLevel = userData.riskTolerance?.[0] || 5;
  const riskProfile = riskLevel <= 3 ? 'Conservative' : riskLevel <= 7 ? 'Moderate' : 'Aggressive';

  const reportSections = [
    {
      title: 'Executive Summary',
      description: 'Overview of your financial profile and key recommendations',
      icon: FileText,
      completed: true
    },
    {
      title: 'Risk Assessment',
      description: 'Detailed analysis of your risk tolerance and capacity',
      icon: Shield,
      completed: true
    },
    {
      title: 'Investment Recommendations',
      description: 'Specific investment strategies tailored to your goals',
      icon: TrendingUp,
      completed: true
    },
    {
      title: 'Portfolio Allocation',
      description: 'Detailed breakdown of recommended asset allocation',
      icon: PieChart,
      completed: true
    },
    {
      title: 'Financial Goals Analysis',
      description: 'Timeline and strategies to achieve your objectives',
      icon: Target,
      completed: true
    },
    {
      title: 'Action Plan',
      description: 'Step-by-step implementation guide',
      icon: CheckCircle,
      completed: true
    }
  ];

  const reportMetrics = [
    {
      label: 'Completeness',
      value: 95,
      description: 'All sections analyzed'
    },
    {
      label: 'Confidence Score',
      value: 88,
      description: 'High confidence in recommendations'
    },
    {
      label: 'Risk-Return Optimization',
      value: 92,
      description: 'Well-balanced approach'
    }
  ];

  const handleDownloadReport = () => {
    // Mock report generation
    const reportData = {
      userData,
      analysisDate: new Date().toISOString(),
      recommendations: [
        'Diversified index fund portfolio',
        'Target-date fund allocation',
        'Emergency fund establishment'
      ]
    };

    // Create a simple text report
    const reportContent = `
FINSIGHT PRO - INVESTMENT ANALYSIS REPORT
=========================================

Generated: ${new Date().toLocaleDateString()}
Client Profile: ${userData.age} years old, ${riskProfile} risk tolerance

EXECUTIVE SUMMARY
-----------------
Investment Amount: $${investmentAmount.toLocaleString()}
Risk Profile: ${riskProfile}
Time Horizon: ${userData.timeHorizon || 'Long-term'}
Investment Experience: ${userData.experience || 'Not specified'}

KEY RECOMMENDATIONS
-------------------
1. Asset Allocation: ${riskLevel <= 4 ? '70% Bonds, 30% Stocks' : riskLevel <= 7 ? '50% Bonds, 50% Stocks' : '20% Bonds, 80% Stocks'}
2. Expected Annual Return: ${riskLevel <= 4 ? '6-8%' : riskLevel <= 7 ? '8-10%' : '10-12%'}
3. Primary Strategy: Diversified index fund portfolio

NEXT STEPS
----------
1. Review and adjust emergency fund
2. Implement recommended portfolio allocation
3. Set up automatic investing schedule
4. Review portfolio quarterly

This report is generated by FinSight Pro AI and should be reviewed with a qualified financial advisor.
    `;

    const blob = new Blob([reportContent], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `FinSight_Pro_Report_${new Date().toISOString().split('T')[0]}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  return (
    <div className="max-w-4xl mx-auto space-y-8">
      {/* Header */}
      <div className="text-center">
        <h2 className="text-3xl font-bold bg-gradient-to-r from-primary to-accent bg-clip-text text-transparent">
          Investment Analysis Report
        </h2>
        <p className="text-muted-foreground mt-2">
          Comprehensive financial analysis and personalized recommendations
        </p>
      </div>

      {/* Report Overview */}
      <Card className="border-border shadow-[var(--shadow-elevated)]">
        <CardHeader>
          <div className="flex items-center justify-between">
            <div>
              <CardTitle className="flex items-center gap-2">
                <FileText className="w-5 h-5 text-accent" />
                Report Overview
              </CardTitle>
              <CardDescription>Generated on {new Date().toLocaleDateString()}</CardDescription>
            </div>
            <Badge variant="secondary" className="bg-success text-success-foreground">
              Complete
            </Badge>
          </div>
        </CardHeader>
        <CardContent>
          <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
            {reportMetrics.map((metric, index) => (
              <div key={index} className="space-y-2">
                <div className="flex justify-between items-center">
                  <span className="text-sm font-medium">{metric.label}</span>
                  <span className="text-lg font-bold text-accent">{metric.value}%</span>
                </div>
                <Progress value={metric.value} className="h-2" />
                <p className="text-xs text-muted-foreground">{metric.description}</p>
              </div>
            ))}
          </div>
        </CardContent>
      </Card>

      {/* Report Contents */}
      <Card className="border-border shadow-[var(--shadow-card)]">
        <CardHeader>
          <CardTitle>Report Contents</CardTitle>
          <CardDescription>Detailed sections included in your analysis</CardDescription>
        </CardHeader>
        <CardContent>
          <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
            {reportSections.map((section, index) => (
              <div key={index} className="flex items-start gap-3 p-4 border rounded-lg">
                <div className="p-2 rounded-lg bg-accent-light">
                  <section.icon className="w-5 h-5 text-accent" />
                </div>
                <div className="flex-1">
                  <div className="flex items-center gap-2 mb-1">
                    <h4 className="font-medium">{section.title}</h4>
                    {section.completed && (
                      <CheckCircle className="w-4 h-4 text-success" />
                    )}
                  </div>
                  <p className="text-sm text-muted-foreground">{section.description}</p>
                </div>
              </div>
            ))}
          </div>
        </CardContent>
      </Card>

      {/* Key Insights */}
      <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
        <Card className="border-border shadow-[var(--shadow-card)]">
          <CardHeader>
            <CardTitle className="flex items-center gap-2">
              <DollarSign className="w-5 h-5 text-accent" />
              Investment Summary
            </CardTitle>
          </CardHeader>
          <CardContent className="space-y-4">
            <div className="space-y-3">
              <div className="flex justify-between">
                <span className="text-sm text-muted-foreground">Investment Amount</span>
                <span className="font-medium">${investmentAmount.toLocaleString()}</span>
              </div>
              <div className="flex justify-between">
                <span className="text-sm text-muted-foreground">Risk Profile</span>
                <span className="font-medium">{riskProfile}</span>
              </div>
              <div className="flex justify-between">
                <span className="text-sm text-muted-foreground">Time Horizon</span>
                <span className="font-medium">{userData.timeHorizon || 'Long-term'}</span>
              </div>
              <div className="flex justify-between">
                <span className="text-sm text-muted-foreground">Expected Return</span>
                <span className="font-medium text-success">
                  {riskLevel <= 4 ? '6-8%' : riskLevel <= 7 ? '8-10%' : '10-12%'} annually
                </span>
              </div>
            </div>
          </CardContent>
        </Card>

        <Card className="border-border shadow-[var(--shadow-card)]">
          <CardHeader>
            <CardTitle className="flex items-center gap-2">
              <Calendar className="w-5 h-5 text-accent" />
              Implementation Timeline
            </CardTitle>
          </CardHeader>
          <CardContent className="space-y-4">
            <div className="space-y-3">
              <div className="flex items-center gap-3">
                <div className="w-2 h-2 bg-accent rounded-full" />
                <div>
                  <p className="text-sm font-medium">Week 1-2</p>
                  <p className="text-xs text-muted-foreground">Set up investment accounts</p>
                </div>
              </div>
              <div className="flex items-center gap-3">
                <div className="w-2 h-2 bg-accent rounded-full" />
                <div>
                  <p className="text-sm font-medium">Week 3-4</p>
                  <p className="text-xs text-muted-foreground">Initial portfolio allocation</p>
                </div>
              </div>
              <div className="flex items-center gap-3">
                <div className="w-2 h-2 bg-muted-foreground rounded-full" />
                <div>
                  <p className="text-sm font-medium">Month 2-3</p>
                  <p className="text-xs text-muted-foreground">Monitor and adjust</p>
                </div>
              </div>
              <div className="flex items-center gap-3">
                <div className="w-2 h-2 bg-muted-foreground rounded-full" />
                <div>
                  <p className="text-sm font-medium">Quarterly</p>
                  <p className="text-xs text-muted-foreground">Portfolio rebalancing</p>
                </div>
              </div>
            </div>
          </CardContent>
        </Card>
      </div>

      {/* Download Section */}
      <Card className="border-border shadow-[var(--shadow-elevated)] bg-gradient-to-r from-accent-light/30 to-primary/5">
        <CardContent className="p-8 text-center">
          <div className="space-y-4">
            <div className="mx-auto w-16 h-16 bg-accent-light rounded-full flex items-center justify-center">
              <Download className="w-8 h-8 text-accent" />
            </div>
            <div>
              <h3 className="text-xl font-bold mb-2">Ready to Download Your Report</h3>
              <p className="text-muted-foreground">
                Get your comprehensive investment analysis report with detailed recommendations and action steps.
              </p>
            </div>
            <div className="flex flex-col sm:flex-row gap-3 justify-center">
              <Button 
                onClick={handleDownloadReport}
                size="lg"
                className="bg-gradient-to-r from-primary to-accent text-primary-foreground hover:shadow-lg transition-[var(--transition-all)]"
              >
                <Download className="w-5 h-5 mr-2" />
                Download Full Report (PDF)
              </Button>
              <Button variant="outline" size="lg">
                <FileText className="w-5 h-5 mr-2" />
                View Executive Summary
              </Button>
            </div>
            <p className="text-xs text-muted-foreground">
              Report includes: Executive summary, risk analysis, investment recommendations, and implementation guide
            </p>
          </div>
        </CardContent>
      </Card>
    </div>
  );
};